name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Create Executable
        shell: cmd
        run: |
          python -m venv .
          Scripts\activate.bat
          Scripts\python.exe -m pip install --upgrade setuptools
          Scripts\python.exe -m pip install pyinstaller
          Scripts\python.exe -m pip install "twisted[tls]" appnope requests certifi
          Scripts\python.exe -m pip install -r requirements.txt
          Scripts\pyinstaller.exe --onefile --add-data "finterface_pscad.f90.tmpl;." IEC_DLL_PSCAD_Import_Tool.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IEC_DLL_PSCAD_Import_Tool
          path: dist/IEC_DLL_PSCAD_Import_Tool.exe

  deploy:
    name: Push builds
    runs-on: ubuntu-latest
    needs: [windows]
  
    permissions:
      contents: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Download WINDOWS artifact
        uses: actions/download-artifact@v4
        with:
          name: IEC_DLL_PSCAD_Import_Tool
  
      - name: Check downloaded files
        run: ls -la
  
      - name: Upload WINDOWS binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./IEC_DLL_PSCAD_Import_Tool.exe
          asset_name: IEC_DLL_PSCAD_Import_Tool.exe
          tag: IEC_DLL_PSCAD_Import_Tool
          overwrite: true
